java.lang.IllegalArgumentException: timeout value is negative at spock.util.concurrent.PollingConditions.within(PollingConditions.java:166) at spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:134) (cherry picked from commit 310f057)