Fix flaky Spring Tests due to Schema Resolution
The schemas URIs where changed to https: with commit(cadc6e920ffc442ab138f30de379f0bf1d1dd814).
But Spring has a special handling for schemas in the class
org.springframework.beans.factory.xml.PluggableSchemaResolver.
This maps schema URIs to Classpath resources shipped with Spring itself.
E.g. the file spring-beans-3.2.16.RELEASE.jar!\META-INF\spring.schemas
defines these resources, which are only mapped with http:// not with https://.

So my guess is, that due to https://, the schema can't be resolved
via classpath, so the test needs to download it,
which can be flaky especially on Windows machines.

When I change the schemas back to http:, they get resolved via classpath resources.

This should prevent the reoccurring flaky tests like:
XmlBeanDefinitionStoreException: Line 5 in XML document from class path
 resource [org/spockframework/spring/InjectionExamples-context.xml]
 is invalid; nested exception is SAXParseException;
 lineNumber: 5; columnNumber: 79; cvc-elt.1:
 Cannot find the declaration of element 'beans'.