Updated net.bytebuddy version
Avoid java.lang.NoSuchMethodError: net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.isAvailable() - method introduced in version 1.8.0